spring:
  redis:
    database: 11
    host: 127.0.0.1
    port: 6379
    timeout: 5000ms
    password: xxx
    lettuce:
      pool:
        max-active: 8
        max-wait: 5000ms
        min-idle: 0
        max-idle: 8

  # datasource
  datasource:
    url: 'jdbc:mysql://127.0.0.1:3306/template?tcpKeepAlive=true&serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf-8'
    username: root
    password: xxx
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 10000
      max-lifetime: 7200000
      idle-timeout: 1800000
      minimum-idle: 5

debug: false
springdoc:
  api-docs:
    enabled: false
knife4j:
  enable: false
  production: true