application-description: '@project.description@'
application-version: '@project.version@'

server:
  servlet:
    context-path: /api
    application-display-name: template-service
  port: 9090
  error:
    whitelabel:
      enabled: false

spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: template-simple-service
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  freemarker:
    check-template-location: false
  thymeleaf:
    check-template-location: false
    cache: false
  task:
    scheduling:
      pool:
        size: 2
    execution:
      pool:
        core-size: 4

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    show-extensions: true
    show-common-extensions: true

knife4j:
  enable: true
  production: false

logging:
  config: classpath:logback-spring.xml


---
# dev ###########################


---
# test ###########################
spring:
  config:
    activate:
      on-profile: test

---
# uat ###########################
spring:
  config:
    activate:
      on-profile: uat

---
# prod ###########################
spring:
  config:
    activate:
      on-profile: prod
debug: false
springdoc:
  api-docs:
    enabled: false
knife4j:
  enable: false
  production: true